"""M1/M2 파이프라인 테스트 — 네트워크/토큰 없이 mock provider + 주입 fetch 로 검증.

핵심 검증: dedup, 엔티티 적재, **기존 그래프와의 연결(머지)**, 관계 검증/적재,
provisional/proposal, vault export.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

import pytest

from claire.ontology.base import Document
from claire.ingest.pipeline import ingest
from claire.ingest.normalize import canonicalize_url, content_hash
from claire.ingest.router import classify
from claire.extract.provider import (
    MockProvider, ExtractionResult, ExtractedEntity, ExtractedRelation,
)
from claire.store import db as dbm
from claire.store.vectors import VectorStore


def _db() -> sqlite3.Connection:
    conn = sqlite3.connect(":memory:")
    conn.row_factory = sqlite3.Row
    dbm.init_db(conn)
    return conn


# --- normalize / router ---

def test_canonicalize_url():
    a = canonicalize_url("https://www.Example.com/Path/?utm_source=x&id=2#frag")
    assert a == "https://example.com/Path?id=2"
    assert canonicalize_url("https://x.com/a/") == "https://x.com/a"


def test_content_hash_stable():
    assert content_hash("a  b") == content_hash(" a b ")
    assert content_hash("a") != content_hash("b")


def test_router_classify():
    assert classify("https://youtu.be/abc") == "youtube"
    assert classify("https://x.com/u/status/1") == "xcom"
    assert classify("https://share.google/zzz") == "redirect"
    assert classify("https://geeknews.io/post") == "web"
    assert classify("그냥 키워드") == "text"


# --- pipeline with mock provider + injected fetch ---

def _fetch_doc(doc: Document):
    return lambda payload: doc


def test_ingest_text_creates_entities_and_vault(tmp_path: Path):
    conn = _db()
    vstore = VectorStore(conn, "brute")
    doc = Document(
        url="https://github.com/safishamsi/graphify",
        title="Graphify",
        raw_text="A knowledge graph generator from any corpus.",
        source_type="web",
        content_hash="h-graphify",
    )
    rep = ingest("x", conn=conn, provider=MockProvider(), vstore=vstore,
                 vault_dir=tmp_path, fetch_fn=_fetch_doc(doc))
    assert rep.error is None
    assert rep.entities_created >= 1
    assert rep.relations_added >= 1  # repo -authored_by-> org
    # vault 파일이 생성되고 generated 배너 + wikilink 포함
    files = list(tmp_path.glob("*.md"))
    assert files
    txt = "\n".join(f.read_text() for f in files)
    assert "generated by claire_bible" in txt
    assert "[[" in txt


def test_dedup_second_ingest_is_skipped():
    conn = _db()
    vstore = VectorStore(conn, "brute")
    doc = Document(title="Dup", raw_text="same", source_type="text", content_hash="dup1")
    p = MockProvider()
    r1 = ingest("x", conn=conn, provider=p, vstore=vstore, fetch_fn=_fetch_doc(doc))
    r2 = ingest("x", conn=conn, provider=p, vstore=vstore, fetch_fn=_fetch_doc(doc))
    assert not r1.duplicate and r2.duplicate
    assert dbm.counts(conn)["documents"] == 1


def test_existing_node_gets_linked_across_documents():
    """핵심 가치: 같은 엔티티가 두 자료에 나오면 하나로 수렴(머지)된다."""
    conn = _db()
    vstore = VectorStore(conn, "brute")

    class P(MockProvider):
        def __init__(self, ents, rels=None):
            self._ents = ents
            self._rels = rels or []

        def extract(self, doc, ontology_block=None):
            return ExtractionResult(
                summary="s",
                entities=[ExtractedEntity(**e) for e in self._ents],
                relations=[ExtractedRelation(**r) for r in self._rels],
            )

    d1 = Document(title="Doc1", raw_text="t1", source_type="text", content_hash="c1")
    d2 = Document(title="Doc2", raw_text="t2", source_type="text", content_hash="c2")

    p1 = P([{"name": "Claude Code", "type": "Tool", "observations": ["from doc1"]}])
    r1 = ingest("x", conn=conn, provider=p1, vstore=vstore, fetch_fn=_fetch_doc(d1))
    assert r1.entities_created == 1

    # 두번째 문서에서 같은 이름(대소문자 다름) → 기존 노드에 연결
    p2 = P([{"name": "claude code", "type": "Tool", "observations": ["from doc2"]}])
    r2 = ingest("x", conn=conn, provider=p2, vstore=vstore, fetch_fn=_fetch_doc(d2))
    assert r2.entities_linked == 1
    assert r2.entities_created == 0
    assert dbm.counts(conn)["entities"] == 1  # 수렴
    ent = dbm.all_entities(conn)[0]
    assert "from doc1" in ent.observations and "from doc2" in ent.observations
    assert len(ent.sources) == 2


def test_relation_domain_range_rejection_and_proposal():
    conn = _db()
    vstore = VectorStore(conn, "brute")

    class P(MockProvider):
        def extract(self, doc, ontology_block=None):
            return ExtractionResult(
                summary="s",
                entities=[
                    ExtractedEntity(name="RepoX", type="Repo"),
                    ExtractedEntity(name="ToolY", type="Tool"),
                    ExtractedEntity(name="ThingZ", type="Gadget",
                                    proposed_type="gadget"),
                ],
                relations=[
                    # authored_by 의 range 는 Person/Org. Tool 타겟 → 거부
                    ExtractedRelation(source="RepoX", target="ToolY", type="authored_by"),
                    # provisional 관계 타입
                    ExtractedRelation(source="RepoX", target="ToolY",
                                      type="forks_from", proposed_type="forks_from"),
                ],
            )

    doc = Document(title="D", raw_text="t", source_type="text", content_hash="ck")
    rep = ingest("x", conn=conn, provider=P(), vstore=vstore, fetch_fn=_fetch_doc(doc))
    assert rep.relations_rejected >= 1   # authored_by 거부
    assert rep.relations_added >= 1      # forks_from(provisional) 적재
    assert rep.proposals >= 1            # gadget + forks_from 제안 기록
    # provisional 엔티티 플래그
    gz = [e for e in dbm.all_entities(conn) if e.name == "ThingZ"][0]
    assert gz.provisional


def test_fetch_error_reported():
    conn = _db()
    vstore = VectorStore(conn, "brute")

    def boom(_payload):
        raise RuntimeError("network down")

    rep = ingest("x", conn=conn, provider=MockProvider(), vstore=vstore, fetch_fn=boom)
    assert rep.error and "network down" in rep.error
    assert dbm.counts(conn)["documents"] == 0
