"""HTTP 본문 수준의 저품질/차단 페이지 사전 필터 (Pre-LLM Content Guard).

웹 페이지 크롤링 시 HTTP 200 등으로 반환되지만 실제로는 봇 차단(Cloudflare, CAPTCHA),
권한 없음(Soft 403), 존재하지 않는 페이지(Soft 404), 로그인/페이월 게이트, 극단적 저밀도
잡음인 경우를 LLM 투입 전 휴리스틱으로 감지해 차단·에스컬레이션한다.
"""

from __future__ import annotations

import re

# 1. 봇 / Cloudflare / CAPTCHA 챌린지 패턴
_CHALLENGE_PATTERNS = (
    r"just a moment\.{2,}",
    r"checking your browser before accessing",
    r"ddos protection by cloudflare",
    r"verify you are human",
    r"verify that you are human",
    r"enable javascript and cookies to continue",
    r"attention required!\s*\|\s*cloudflare",
    r"please complete the security check",
    r"please enable cookies and refresh the page",
    r"cf-browser-verification",
    r"cf-chl-bypass",
    r"recaptcha challenge",
    r"hcaptcha challenge",
    r"generated by cloudfront.*request blocked",
    r"access to this page has been denied because we believe you are using automation tools",
)
_CHALLENGE_RE = re.compile("|".join(f"(?:{p})" for p in _CHALLENGE_PATTERNS), re.IGNORECASE)

# 2. Soft 403 / Access Denied 패턴
_ACCESS_DENIED_PATTERNS = (
    r"^(?:403\s+forbidden|401\s+unauthorized|access\s+denied|permission\s+denied)\b",
    r"you don't have permission to access",
    r"you do not have permission to access",
    r"access to this page is denied",
    r"error\s+403\s*:\s*forbidden",
    r"request blocked by administrative rules",
)
_ACCESS_DENIED_RE = re.compile("|".join(f"(?:{p})" for p in _ACCESS_DENIED_PATTERNS), re.IGNORECASE)

# 3. Soft 404 / Page Not Found 패턴
_NOT_FOUND_TITLE_PATTERNS = (
    r"^(?:404\s*[-:|]?\s*page\s*not\s*found|page\s*not\s*found\s*[-:|]?\s*404|404\s*not\s*found)\b",
    r"^(?:페이지를\s*찾을\s*수\s*없습니다|존재하지\s*않는\s*페이지|요청하신\s*페이지를\s*찾을\s*수\s*없습니다)",
    r"^(?:page\s*not\s*found|not\s*found\s*404|error\s*404)\b",
)
_NOT_FOUND_TITLE_RE = re.compile("|".join(f"(?:{p})" for p in _NOT_FOUND_TITLE_PATTERNS), re.IGNORECASE)

_NOT_FOUND_BODY_PATTERNS = (
    r"the page you (?:are looking for|requested) (?:could not be found|does not exist|has been removed)",
    r"this page could not be found",
    r"we couldn't find the page you're looking for",
    r"page (?:you are looking for|requested) is not available",
    r"페이지가\s*(?:삭제되었거나|존재하지|사라졌)",
    r"찾으려는\s*페이지의\s*주소가\s*잘못",
    r"요청하신\s*페이지를\s*찾을\s*수\s*없습니다",
)
_NOT_FOUND_BODY_RE = re.compile("|".join(f"(?:{p})" for p in _NOT_FOUND_BODY_PATTERNS), re.IGNORECASE)

# 4. Login / Paywall 게이트 패턴
_PAYWALL_PATTERNS = (
    r"sign in to (?:continue|read|view)",
    r"log in to (?:continue|read|view)",
    r"subscribe to (?:continue|read the full|unlock)",
    r"join linkedin to view",
    r"create a free account to (?:continue|read)",
    r"you have reached your limit of free articles",
)
_PAYWALL_RE = re.compile("|".join(f"(?:{p})" for p in _PAYWALL_PATTERNS), re.IGNORECASE)


def validate_web_content(title: str | None, text: str | None) -> tuple[bool, str | None]:
    """본문이 정상 콘텐츠인지 사전 검증. (ok: bool, reason: str | None).
    
    차단/저품질로 판단되면 (False, "사유")를 반환하여 에스컬레이션 또는 FetchError 처리를 유도한다.
    """
    if not text:
        return False, "empty_content"
    
    t = text.strip()
    title_str = (title or "").strip()
    length = len(t)
    
    # 1. 봇 / Cloudflare / CAPTCHA 챌린지 (챌린지 페이지는 대개 3000자 미만)
    if length < 3000:
        if _CHALLENGE_RE.search(title_str) or _CHALLENGE_RE.search(t):
            return False, "blocked: bot_challenge"

    # 2. Soft 403 / Access Denied (짧은 차단 페이지)
    if length < 2000:
        if _ACCESS_DENIED_RE.search(title_str) or _ACCESS_DENIED_RE.search(t[:600]):
            return False, "blocked: access_denied"

    # 3. Soft 404 / Page Not Found (짧은 404 페이지)
    if length < 2000:
        if _NOT_FOUND_TITLE_RE.search(title_str):
            return False, "low_quality: not_found"
        if _NOT_FOUND_BODY_RE.search(t[:1000]) and length < 1200:
            return False, "low_quality: not_found"

    # 4. Login / Paywall 게이트 (짧은 본문에서 CTA 주도)
    if length < 800:
        if _PAYWALL_RE.search(t[:800]):
            return False, "low_quality: paywall_or_login"

    # 5. 극단적 텍스트 밀도 저하 / 반복 잡음 검증
    # 알파뉴메릭(한글/영문/숫자) 비율이 전체의 30% 미만인 경우 (단, 최소 300자 이상에서 검사)
    if length >= 300:
        alphanumeric_count = sum(1 for c in t if c.isalnum())
        if alphanumeric_count / length < 0.30:
            return False, "low_quality: low_alphanumeric_density"

    return True, None
