"""Obsidian 호환 vault export (단방향, generated).

advisor 조언: SQLite 정본, vault 는 export-only. 모든 .md 에 generated 배너를 박아
손편집이 덮어써지는 사고를 방지한다. 관계는 [[wikilink]] 로 표현 → 옵시디언 그래프뷰.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

from slugify import slugify

from ..ontology.base import Entity
from ..store import db as dbm

BANNER = "<!-- generated by claire-bible — do not edit; source of truth is the SQLite DB -->"


def _entity_filename(ent: Entity) -> str:
    return f"{slugify(ent.name) or ent.id}-{ent.id[-6:]}.md"


def export_entity(conn: sqlite3.Connection, vault_dir: Path, ent: Entity) -> Path:
    vault_dir.mkdir(parents=True, exist_ok=True)
    rels = dbm.neighbors(conn, ent.id)

    lines = [BANNER, "---"]
    lines.append(f"id: {ent.id}")
    lines.append(f"type: {ent.type}")
    if ent.provisional:
        lines.append("provisional: true")
    if ent.aliases:
        lines.append(f"aliases: [{', '.join(ent.aliases)}]")
    lines.append("---")
    lines.append("")
    lines.append(f"# {ent.name}")
    lines.append("")

    if ent.observations:
        lines.append("## Observations")
        for o in ent.observations:
            lines.append(f"- {o}")
        lines.append("")

    if rels:
        lines.append("## Relations")
        for r in rels:
            other_id = r.target_id if r.source_id == ent.id else r.source_id
            other = dbm.get_entity(conn, other_id)
            if not other:
                continue
            arrow = "→" if r.source_id == ent.id else "←"
            tag = f"{r.type}{'*' if r.provisional else ''}"
            lines.append(f"- {arrow} **{tag}** [[{slugify(other.name) or other.id}]]")
        lines.append("")

    if ent.sources:
        lines.append("## Sources")
        for s in ent.sources:
            lines.append(f"- {s}")
        lines.append("")

    path = vault_dir / _entity_filename(ent)
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def export_entities(conn: sqlite3.Connection, vault_dir: Path, entities: list[Entity]) -> list[Path]:
    return [export_entity(conn, vault_dir, e) for e in entities]
